[package]
name = "biomass-breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.2"
rusttype = "0.9.2"
cgmath = "0.18.0"
